services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/10-create-user-and-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U program -d persons"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://program:test@db:5432/persons
    depends_on:
      db:
        condition: service_healthy
